apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-test-web
  template:
    metadata:
      labels:
        app: k8s-test-web
    spec:
      containers:
      - name: k8s-test-web
        image: gasstin/k8s-test-web
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
